// Generated by CoffeeScript 1.9.1
var Person, exports;

Person = (function() {
  function Person(name) {
    this.name = name;
  }

  Person.prototype.say = function(msg) {
    return console.log(this.name + " says " + msg);
  };

  return Person;

})();

exports = module.exports = Person;
