// Generated by CoffeeScript 1.9.1
var Customer, Person, ken, tom;

Person = require('./Person');

Customer = require('./Customer');

tom = new Person('Tom');

tom.say('hello!');

ken = new Customer('Ken', 'vip');

ken.order('book');
