# Generated by CoffeeScript 1.8.0
assert = undefined
rest = undefined
assert = require("chai").assert
rest = require("restler")
describe "Test examples", ->
  it "should GET rest api", (done) ->
    rest.get("http://localhost:3000/").on "complete", (result) ->
      if result instanceof Error
        console.log "Error:", result.message
        assert["throw"] result.message
      else
        console.log result
        assert.equal result, "home", "server does not return \"home\""
      done()
      return

    return

  it "should POST rest api", (done) ->
    rest.post("http://localhost:3000/signup",
      data:
        email: "tom@gmail.com"
        name: "Tom"
    ).on "complete", (data, response) ->
      console.log data
      console.log data.name
      assert.equal data.name, "Tom", "name is not \"Tom\""
      console.log response.statusCode
      assert.equal response.statusCode, 200, "response.statusCode is not 200"
      done()
      return

    return

  it "should do a synchronous test", ->
    assert.ok true
    return

  it "should do an asynchronous test", (done) ->
    setTimeout (->
      assert.ok true
      done()
      return
    ), 15
    return

  return
